config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index]
  root to: "books#index"
  match '/books/:isbn' => 'books#show', :as => 'books_show', via: [:get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book

  def initialize(title, author)
    @title = title
    @author = author

    @description = ""
    @isbn = nil
    @img_url = ""
    @nps_score = 0
    @google_buy_url = nil
    @total_reviews = 0
  end

  def nps_color_class
    if @nps_score >= 0 and @nps_score <= 10
      return 'good-nps'
    elsif @nps_score > 10 and @nps_score <= 35
      return 'great-nps'
    elsif @nps_score > 35
      return 'amazing-nps'
    elsif @nps_score < 0 and @nps_score >= -10
      return 'bad-nps'
    elsif @nps_score < -10 and @nps_score >= -35
      return 'really-bad-nps'
    else
      return 'awful-nps'
    end
  end

  def nps_description_word
    if @nps_score >= -5 and @nps_score <= 5
      return 'Regular'
    elsif @nps_score > 5 and @nps_score <= 25
      return 'Good'
    elsif @nps_score > 25
      return 'Great'
    elsif @nps_score < -5 and @nps_score >= -25
      return 'Bad'
    else
      return 'Really Bad'
    end
  end

  def title
    @title
  end

  def author
    @author
  end

  def description
    @description
  end

  def description= description
    @description = description
  end

  def isbn
    @isbn
  end

  def isbn= isbn
    @isbn = isbn
  end

  def img_url
    @img_url
  end

  def img_url= img_url
    @img_url = img_url
  end

  def nps_score
    @nps_score
  end

  def nps_score= nps_score
    @nps_score = nps_score
  end

  def publisher
    @publisher
  end

  def publisher= publisher
    @publisher = publisher
  end

  def page_count
    @page_count
  end

  def page_count= page_count
    @page_count = page_count
  end

  def categories
    @categories
  end

  def categories= categories
    @categories = categories
  end

  def total_reviews
    @total_reviews
  end

  def total_reviews= total_reviews
    @total_reviews = total_reviews
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @date = Date.today.end_of_week(:monday)
    if params[:search]
      formatted_search = params[:search].downcase.split(' ').join('+')
      response = Typhoeus.get("https://www.googleapis.com/books/v1/volumes?q=#{formatted_search}&key:AIzaSyAhhshz7DlcDYgVbDWLCrXZLfMxlVdMYYA", followlocation: true)
      body = JSON.parse(response.body)

      responseBooks = body["items"]

      @responseType = "google"

      @books = get_sorted_books(responseBooks, @responseType)
    else
      queryDate = @date.strftime("%Y-%m-%d")
      if params[:date]
        queryDate = params[:date]
        @date = params[:date].to_datetime
      end

      response = Typhoeus.get("https://api.nytimes.com/svc/books/v3/lists.json?api-key=ec2d52743558402883a87a233a9b1af7&list=combined-print-and-e-book-fiction&date=#{queryDate}", followlocation: true)
      body = JSON.parse(response.body)

      responseBooks = body["results"]

      @responseType = "nyTimes"

      @books = get_sorted_books(responseBooks, @responseType)
    end
  end

  def show
    response = Typhoeus.get("https://www.googleapis.com/books/v1/volumes?q=#{params[:isbn]}+isbn&key:AIzaSyAhhshz7DlcDYgVbDWLCrXZLfMxlVdMYYA", followlocation: true)

    body = JSON.parse(response.body)

    responseBooks = body["items"]
    volumeInfo = responseBooks[0]["volumeInfo"]
    saleInfo = responseBooks[0]["saleInfo"]

    goodreadsResponse = Typhoeus.get("https://www.goodreads.com/book/isbn/#{params[:isbn].to_i}?key=Rf1LgjsOB2cf69K4gMbPkQ", followlocation: true)

    # Create a hash from the xml data and then symbolize it
    hash = Hash.from_xml(goodreadsResponse.body.gsub("\n", ""))
    symbolized_hash = hash.symbolize_keys

    # Get data from hash
    bookData = symbolized_hash[:GoodreadsResponse]["book"]

    @book = Book.new(params[:title], params[:author])
    @book.nps_score = params[:nps].to_f
    @book.img_url = volumeInfo["imageLinks"]["thumbnail"]

    @book.publisher = volumeInfo["publisher"]
    @book.page_count = volumeInfo["pageCount"]
    @book.categories = volumeInfo["categories"]
    @book.description = bookData["description"]

  end

end

private
def get_sorted_books(responseBooks, responseType)
  books = Array.new

  hydra = Typhoeus::Hydra.new
  responseBooks.each_with_index do |responseBook, index|

    title = ""
    author = ""
    isbns = Array.new
    queryISBN = 0
    if responseType == "nyTimes"
      title = responseBook["book_details"][0]["title"]
      author = responseBook["book_details"][0]["author"]
      isbns = responseBook["isbns"]
      next if isbns.empty?
      queryISBN = isbns[0]["isbn13"].to_i
    elsif responseType == "google"
      title = responseBook["volumeInfo"]["title"]
      author = responseBook["volumeInfo"]["authors"].nil? ? "" : responseBook["volumeInfo"]["authors"][0]
      isbns = responseBook["volumeInfo"]["industryIdentifiers"]

      if !isbns.nil?
        isbns.each do |isbn|
          if isbn["type"] == "ISBN_13"
            queryISBN = isbn["identifier"]
          end
        end
      end
      if queryISBN == 0 && !isbns.nil?
        if isbns[0]["type"] != "ISBN_10"
          next
        end
        queryISBN = isbns[0]["identifier"]
      end
    end

    book = Book.new(title, author)
    book.isbn = queryISBN

    # Create a request for each book
    request = Typhoeus::Request.new("https://www.goodreads.com/book/isbn/#{book.isbn}?key=Rf1LgjsOB2cf69K4gMbPkQ", followlocation: true)

    # Handle the requests
    request.on_complete do |response|
      if response.success?
        # Create a hash from the xml data and then symbolize it
        hash = Hash.from_xml(response.body.gsub("\n", ""))
        symbolized_hash = hash.symbolize_keys

        # Get data from
        data = symbolized_hash[:GoodreadsResponse]
        book.img_url = data["book"]["image_url"]
        rating_dist = data["book"]["work"]["rating_dist"]

        split_rating = rating_dist.split('|')

        # Get total count and check if there are ratings
        total_count = split_rating[5].split(':')[1].to_i
        if total_count != 0
          promoter_count = 0.0
          detractor_count = 0.0

          # Get the count of 5 star ratings
          promoter_count = split_rating[0].split(':')[1].to_i

          # Get the count from 3 to 1 star ratings
          (2..4).each do |i|
            detractor_count += split_rating[i].split(':')[1].to_i
          end

          # Calculate percentages
          promoter_percentage = (promoter_count * 100) / total_count
          detractor_percentage = (detractor_count * 100) / total_count

          # Calculate nps score and append it
          nps_score = promoter_percentage - detractor_percentage
          book.total_reviews = total_count
          book.nps_score = nps_score

        else
          book.nps_score = 0
        end
      else
        next
      end
      books << book
    end
    # Add each request to hydra queue
    hydra.queue(request)
  end
  # Run all the requests
  hydra.run

  # return sorted array
  return books.sort! { |a,b| b.nps_score <=> a.nps_score }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def get_prev_date(date)
    date = date - 7
    return date.strftime("%Y-%m-%d")
  end

  def get_next_date(date)
    date = date + 7
    return date.strftime("%Y-%m-%d")
  end

  def get_categories_string(categories)
    str = ""
    categories.each_with_index do |category, index|
      if index == categories.count - 1
        str << category
      else
        str = str + category + ", "
      end
    end
  end
end

app/views/books/index.html.erb
<div class="container book-grid">
  <div class="date-picker" style="text-align: right">
    <%= link_to books_path({ :date => get_prev_date(@date) }) do %>
      <i class="fa fa-chevron-left" style="margin-right: 5px;"></i>
    <% end %>
    <span><%= @date.strftime('%b %-d, %Y') %></span>
    <% if @date != Date.today.end_of_week(:monday) %>
      <%= link_to books_path({ :date => get_next_date(@date) }) do %>
        <i class="fa fa-chevron-right"style="margin-left: 5px;"></i>
      <% end %>
    <% end %>
  </div>
  <% if @responseType == "nyTimes" %>
    <h1>Best Sellers</h1>
    <div class="center-divider blue"></div>
  <% elsif @responseType == "google" %>
    <h1>Search Results</h1>
    <div class="center-divider green"></div>
  <% end %>

  <% @books.each_with_index do |book, index| %>
    <div class="row row-item">
      <%= link_to books_show_path(book.isbn, {:title => book.title.split.map(&:capitalize).join(' '), :author => book.author, :nps => book.nps_score.round(1)}), class: "book-link" do %>
      <div class="nps-score-holder <%= book.nps_color_class %> bg">
        <%= book.nps_score.round(1) %>
      </div>
      <div style="float: left;">
        <%= image_tag(book.img_url, :alt => book.title, class: "book-cover") %>
      </div>
      <div class="book-content">
        <h3 class="book-title">
          <%= book.title.split.map(&:capitalize).join(' ') %>
        </h3>
        <p>
          by <%= book.author %>
        </p>
        <p class="book-review-count">
          Based on reviews by <%= book.total_reviews %> <i class="fa fa-users"></i>
        </p>
      </div>
      <% end %>
      <img src="http://authoridentity.com/wp-content/uploads/2015/02/Amazon-preorder.png" alt="Amazon Order" class="buy-img-index">
    </div>
    <% if index != @books.count - 1 %>
      <div class="horizontal-divider"></div>
    <% end %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="show-page">
  <div class="row book-info">
    <div class="col-md-2">
      <%= image_tag(@book.img_url, :alt => @book.title, class: "book-cover-lg") %>
    </div>
    <div class="col-md-6">
      <h1><%= @book.title %></h1>
      <h3><%= @book.author %></h3>
      <div class="book-details">
        <h4>Score</h4>
        <h2><%= @book.nps_score %></h2>
        <h3><span class="<%= @book.nps_color_class %>"><%= @book.nps_description_word %></span></h3>
      </div>
    </div>
    <div class="col-md-4" style="text-align: center">
      <img src="http://authoridentity.com/wp-content/uploads/2015/02/Amazon-preorder.png" alt="Amazon Order" class="buy-img">
    </div>
  </div>
  <div class="horizontal-divider"></div>
  <div class="row">
    <div class="container">
      <div class="col-md-8 description">
        <p>
          <%= sanitize @book.description %>
        </p>
      </div>
      <div class="col-md-1 vcenter" style="width: 0;">
        <div class="vertical-divider"></div>
      </div><!--
      --><div class="col-md-3 vcenter" style="padding: 0">
        <p>
          <span>Publisher: </span><%= @book.publisher %>
        </p>
        <p>
          <span>Pages: </span><%= @book.page_count %>
        </p>
        <p>
          <span>Categories: <span><%= get_categories_string(@book.categories) %></span></span>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Promoter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-white">
      <a class="navbar-brand" href="<%= root_url %>">Book Promoter</a>

      <%= form_tag books_path, :method => 'get', class: "form-inline float-xs-right" do %>
        <p style="margin-bottom: 0">
          <%= text_field_tag :search, params[:search], class: "form-control search-bar", placeholder: "Search" %>
          <%= submit_tag "Search", :name => nil, class: "btn btn-nav-search" %>
        </p>
      <% end %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <div class="footer">
      <p>
        Built by Carlos Diez <a href="https://github.com/cdiezmoran/nps-books-Rails"><%= icon('github', class: 'white-git') %></a>
      </p>
      <h3 style="margin-bottom: 35px;">Powered By</h3>
      <div class="row">
        <div class="col-md-4">
          <a href="https://www.goodreads.com/">
            <img  class="gr-logo" src="https://davescomputertips.com/wp-content/uploads/2016/11/goodreads.png" alt="">

          </a>
        </div>
        <div class="col-md-4" style="background-color: #fff">
          <a href="https://books.google.com/">
            <img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Google_Books_logo_2015.PNG" alt="">
          </a>
        </div>
        <div class="col-md-4">
          <a href="http://www.nytimes.com/books/best-sellers/">
            <img class="" src="http://www.jmarkpowell.com/wp-content/uploads/2015/04/NY-Times-best-seller.png" alt="">
          </a>
        </div>
      </div>
    </div>
  </body>
</html>